version: '3'

services:
  postgresql:
    image: mdillon/postgis:9.6-alpine
    environment:
      - POSTGRES_USER=syncano
      - POSTGRES_PASSWORD=syncano
      - POSTGRES_DB=syncano
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432"

  redis:
    image: redis:3.2-alpine
    volumes:
      - data-redis:/data
    ports:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.6-alpine
    volumes:
      - data-rabbitmq:/data
    ports:
      - "5672"
      - "15672"

  zipkin:
    image: openzipkin/zipkin:1.26
    ports:
      - "9411"

  proxy:
    image: haproxy:1.8-alpine
    ports:
      - "80:80"
      - "90:90"
    depends_on:
      - web
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  web:
    image: quay.io/syncano/syncano-platform:test
    build:
      context: .
      dockerfile: Dockerfile.test
    privileged: true
    ports:
      - "8100"
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/syncano/app
    environment:
      - INSTANCE_TYPE=web
      - API_DOMAIN=api.syncano.test
      - AUTORELOAD=true
      - ANALYTICS_WRITE_KEY
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - STORAGE_BUCKET
      - CI
      - COLORS_ENABLED=true
      - DB_INSTANCES_NAME
      - DJANGO_DEBUG=true
      - DOCKER_HOST_DIRECTORY
      - LEGACY_CODEBOX_ENABLED=true
      - PARALLEL_COUNT
      - SPACE_DOMAIN=syncano_space.test
      - STRIPE_SECRET_KEY
      - TEST_MIGRATIONS
      - TRACING_ENABLED

  worker:
    image: quay.io/syncano/syncano-platform:test
    build:
      context: .
      dockerfile: Dockerfile.test
    privileged: true
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    volumes:
      - .:/home/syncano/app
    environment:
      - INSTANCE_TYPE=worker
      - ANALYTICS_WRITE_KEY
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - STORAGE_BUCKET
      - COLORS_ENABLED=true
      - DJANGO_DEBUG=true
      - LEGACY_CODEBOX_ENABLED=true
      - STRIPE_SECRET_KEY
      - TRACING_ENABLED

  codebox:
    image: quay.io/syncano/syncano-platform:test
    build:
      context: .
      dockerfile: Dockerfile.test
    privileged: true
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/syncano/app
    environment:
      - INSTANCE_TYPE=codebox
      - CODEBOX_RUNNER_CONCURRENCY=2
      - COLORS_ENABLED=true
      - LEGACY_CODEBOX_ENABLED=true

  codebox-broker:
    command: codebox --debug broker
    image: quay.io/syncano/codebox
    depends_on:
      - codebox-lb
    ports:
      - "9000:9000"
      - "8080:8080"
    environment:
      - LB_ADDRS=codebox-lb:9000
      - SERVICE_NAME=codebox-broker

  codebox-lb:
    command: codebox --debug lb
    image: quay.io/syncano/codebox
    environment:
      - SERVICE_NAME=codebox-lb

  codebox-worker:
    command: codebox --debug worker
    user: root
    image: quay.io/syncano/codebox
    privileged: true
    depends_on:
      - codebox-lb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/storage:/home/codebox/storage
    environment:
      - HOST_STORAGE_PATH=/tmp/storage
      - LB_ADDR=codebox-lb:9000
      - SERVICE_NAME=codebox-worker

volumes:
  data-rabbitmq:
  data-redis:
